# Generated by Django 4.2.4 on 2023-08-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
