# Generated by Django 4.2.4 on 2023-08-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_name_person_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_name',
            new_name='name',
        ),
    ]
