# Generated by Django 4.2.4 on 2023-08-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_rename_person_name_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='p_name',
        ),
    ]
