# Generated by Django 4.2.4 on 2023-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_rename_name_person_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='p_name',
            new_name='name',
        ),
    ]
