# Generated by Django 4.2.4 on 2023-08-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_rename_p_name_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=100)),
                ('date_acquired', models.DateField()),
                ('Customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to='demoapp.person')),
            ],
        ),
    ]
