# Generated by Django 4.2.4 on 2023-08-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_remove_person_age_remove_person_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100)),
                ('date_acquired', models.DateField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to='demoapp.person')),
            ],
        ),
    ]
