# Generated by Django 4.2.4 on 2023-08-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_loans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='demoapp.person'),
        ),
    ]
