# Generated by Django 4.2.4 on 2023-08-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_alter_loans_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='id',
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
