# Generated by Django 4.2.4 on 2023-08-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_remove_loans_id_loans_loan_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
