# Generated by Django 4.2.4 on 2023-08-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0013_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='cutomer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Customer_ID', to='demoapp.person'),
        ),
    ]
