# Generated by Django 4.2.4 on 2023-08-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_rename_cutomer_id_loans_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
