# Generated by Django 4.2.4 on 2023-08-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0016_rename_customer_id_loans_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_ID', to='demoapp.person'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_type',
            field=models.CharField(choices=[('short', 'Short'), ('intermediate', 'Intermediate'), ('long', 'Long')], max_length=100),
        ),
    ]
