# Generated by Django 4.2.4 on 2023-08-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_loan_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_req',
            name='type_of_loan',
            field=models.CharField(choices=[('short', 'Short'), ('intermediate', 'Intermediate'), ('long', 'Long')], max_length=100),
        ),
    ]
