# Generated by Django 4.2.4 on 2023-08-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_alter_loan_req_type_of_loan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
    ]
