# Generated by Django 4.2.4 on 2023-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0021_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_req',
            name='time_log',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
