# Generated by Django 4.2.4 on 2023-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0022_alter_loan_req_time_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time_log',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
