# Generated by Django 4.2.4 on 2023-08-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0024_remove_loan_loan_type_loan_loan_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_req',
            new_name='Loan_Requests',
        ),
    ]
