# Generated by Django 4.2.4 on 2023-08-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0025_rename_loan_req_loan_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_Requests',
            new_name='Loan_Request',
        ),
    ]
