# Generated by Django 4.2.4 on 2023-08-12 22:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0027_rename_loan_request_loan_req_remove_loan_loan_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration', models.DurationField()),
            ],
        ),
    ]
