# Generated by Django 4.2.4 on 2023-08-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0028_loan_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_fund',
            old_name='interest_rate',
            new_name='interest_rate_percentage',
        ),
        migrations.RemoveField(
            model_name='loan_fund',
            name='duration',
        ),
    ]
