# Generated by Django 4.2.4 on 2023-08-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0029_rename_interest_rate_loan_fund_interest_rate_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_fund',
            old_name='max',
            new_name='max_EGP',
        ),
        migrations.RenameField(
            model_name='loan_fund',
            old_name='min',
            new_name='min_EGP',
        ),
    ]
