# Generated by Django 4.2.4 on 2023-08-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0030_rename_max_loan_fund_max_egp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan_fund',
        ),
    ]
