# Generated by Django 4.2.4 on 2023-08-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0031_delete_loan_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimum_Amount', models.IntegerField()),
                ('Maximum_Amount', models.IntegerField()),
                ('Interest_Rate', models.IntegerField()),
                ('Duration_in_Days', models.IntegerField()),
            ],
        ),
    ]
