# Generated by Django 4.2.4 on 2023-08-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0032_loan_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute_to_Loan_Fund',
            fields=[
                ('loan_fund_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demoapp.loan_fund')),
                ('Amount', models.IntegerField()),
            ],
            bases=('demoapp.loan_fund',),
        ),
    ]
