# Generated by Django 4.2.4 on 2023-08-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0033_contribute_to_loan_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_fund',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Contribute_to_Loan_Fund',
        ),
    ]
