# Generated by Django 4.2.4 on 2023-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0034_loan_fund_name_delete_contribute_to_loan_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute_to_Loan_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Short Term Investment', ''), ('Long term Investment', '')], max_length=200)),
            ],
        ),
    ]
