# Generated by Django 4.2.4 on 2023-08-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0035_contribute_to_loan_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute_to_loan_fund',
            name='name',
            field=models.CharField(choices=[('Short Term Investment', 'Short Term Investment'), ('Long term Investment', 'Long term Investment')], max_length=200),
        ),
    ]
