# Generated by Django 4.2.4 on 2023-08-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0040_contribute_to_loan_fund_name_of_fund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
