# Generated by Django 4.2.4 on 2023-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0041_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest_in_Loan_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Name', max_length=200)),
                ('Name_of_Fund', models.CharField(choices=[('Check Loan Funds First', 'Check Loan Funds First')], default=None, help_text='Check Loan Funds for the available investments', max_length=200)),
                ('Amount', models.IntegerField(default=None)),
                ('date_of_deposit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Loan_Fund',
            new_name='Loan_Funding_Options',
        ),
        migrations.DeleteModel(
            name='Contribute_to_Loan_Fund',
        ),
    ]
