# Generated by Django 4.2.4 on 2023-08-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0042_invest_in_loan_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_in_loan_fund',
            name='Name_of_Fund',
            field=models.CharField(choices=[('Check Loan Funds First', 'Check Loan Funds First')], default=None, help_text='Check Loan Funding Options for the available investments', max_length=200),
        ),
    ]
