# Generated by Django 4.2.4 on 2023-08-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0043_alter_invest_in_loan_fund_name_of_fund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_Funding_Options',
            new_name='Loan_Funding_Option',
        ),
    ]
