# Generated by Django 4.2.4 on 2023-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0044_rename_loan_funding_options_loan_funding_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest_in_loan_fund',
            name='name',
        ),
        migrations.AddField(
            model_name='invest_in_loan_fund',
            name='full_name',
            field=models.CharField(default=None, help_text='Enter Your Full Name', max_length=200),
        ),
    ]
