# Generated by Django 4.2.4 on 2023-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0045_remove_invest_in_loan_fund_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_loan', models.CharField(max_length=200)),
                ('Minimum_Amount', models.IntegerField()),
                ('Maximum_Amount', models.IntegerField()),
                ('Interest_Rate', models.IntegerField()),
                ('Duration_in_Days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default=None, help_text='Enter Your Full Name', max_length=200)),
                ('type_of_loan', models.CharField(choices=[('Short Term Fund', 'Short Term Fund'), ('Long term Fund', 'Long term Fund'), ('Intermediate Fund', 'Intermediate Fund')], default=None, help_text='Check Loan Options First', max_length=200)),
                ('Amount', models.IntegerField(default=None)),
                ('date_of_request', models.DateTimeField(auto_now=True)),
                ('approval', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
    ]
