# Generated by Django 4.2.4 on 2023-08-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0046_loan_options_loan_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_options',
            new_name='Loan_option',
        ),
        migrations.AlterField(
            model_name='loan_request',
            name='type_of_loan',
            field=models.CharField(choices=[('Check Loan Options First', 'Check Loan Options First')], default=None, help_text='Check Loan Options First', max_length=200),
        ),
    ]
