# Generated by Django 4.2.4 on 2023-08-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0048_remove_loan_request_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='Total_funding',
            field=models.IntegerField(default=None),
        ),
    ]
