# Generated by Django 4.2.4 on 2023-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0049_total_total_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default=None, help_text='Enter Your Full Name', max_length=200)),
                ('type_of_loan', models.CharField(choices=[('Check Loan Options First', 'Check Loan Options First')], default=None, help_text='Check Loan Options First', max_length=200)),
                ('Amount', models.IntegerField(default=None)),
                ('date_of_request', models.DateTimeField(auto_now=True)),
                ('Approval', models.BooleanField(default=False)),
            ],
        ),
    ]
