# Generated by Django 4.2.4 on 2023-08-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0050_loan_approvals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_approvals',
            new_name='Loan_approval',
        ),
    ]
