# Generated by Django 4.2.4 on 2023-08-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0051_rename_loan_approvals_loan_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('approve', 'Approve'), ('pending', 'Pending'), ('reject', 'Reject')], max_length=200),
        ),
    ]
