# Generated by Django 4.2.4 on 2023-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0053_loan_approval_comments_alter_loan_approval_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, help_text='Enter Your Full Name', max_length=200)),
                ('Name_of_Fund', models.CharField(choices=[('Check Loan Funds First', 'Check Loan Funds First')], default=None, help_text='Check Loan Funding Options for the available investments', max_length=200)),
                ('Amount', models.IntegerField(default=None)),
                ('date_of_deposit', models.DateTimeField(auto_now=True)),
                ('Deposit_Confirmation', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Approve'), ('reject', 'Reject')], default='pending', max_length=200)),
                ('Comments', models.TextField(default='', help_text='Reason of Rejection', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('approve', 'Approve'), ('pending', 'Pending'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Comments',
            field=models.TextField(default='', help_text='Reason of Rejection', max_length=2000),
        ),
    ]
