# Generated by Django 4.2.4 on 2023-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0057_alter_investment_approval_deposit_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_in_loan_fund',
            name='Name_of_Fund',
            field=models.CharField(choices=[('Check Loan Fund First', 'Check Loan Funding Options First')], default=None, help_text='Check Loan Funding Options for the available investments', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Comments',
            field=models.TextField(blank=True, default='', help_text='Reason of Rejection', max_length=2000),
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Approve'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Name_of_Fund',
            field=models.CharField(choices=[('Check Loan Fund First', 'Check Loan Funding Options First')], default=None, help_text='Only choose when you have looked at the Investments Options', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='pending', max_length=200),
        ),
    ]
