# Generated by Django 4.2.4 on 2023-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0058_alter_invest_in_loan_fund_name_of_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
    ]
