# Generated by Django 4.2.4 on 2023-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0059_alter_loan_approval_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('confirm', 'Approve'), ('pending', 'Pending'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='pending', max_length=200),
        ),
    ]
