# Generated by Django 4.2.4 on 2023-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0060_alter_investment_approval_deposit_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_in_loan_fund',
            name='Name_of_Fund',
            field=models.CharField(choices=[('Check Loan Fund First', 'Check Loan Funding Options First')], default=None, help_text='Only choose when you have looked at the Investments Options', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('reject', 'Reject'), ('confirm', 'Approve'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Name_of_Fund',
            field=models.CharField(choices=[('Check Loan Fund First', 'Check Loan Funding Options First')], default=None, help_text='Only choose when you have looked at the Investment Options', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
