# Generated by Django 4.2.4 on 2023-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0061_alter_invest_in_loan_fund_name_of_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('reject', 'Reject'), ('pending', 'Pending'), ('approve', 'Approve')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='type_of_loan',
            field=models.CharField(choices=[('Check Loan Options First', 'Check Loan Options First')], default=None, help_text='Only choose when you have looked at the Loan Options First', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_request',
            name='type_of_loan',
            field=models.CharField(choices=[('Check Loan Options First', 'Check Loan Options First')], default=None, help_text='Only choose when you have looked at the Loan Options First', max_length=200),
        ),
        migrations.AlterField(
            model_name='total',
            name='Total_funding',
            field=models.IntegerField(default=0),
        ),
    ]
