# Generated by Django 4.2.4 on 2023-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0062_alter_loan_approval_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('reject', 'Reject'), ('pending', 'Pending'), ('confirm', 'Approve')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Comments',
            field=models.TextField(blank=True, default='', help_text='Reason of Rejection', max_length=2000),
        ),
        migrations.AlterField(
            model_name='total',
            name='Total_funding',
            field=models.IntegerField(),
        ),
    ]
