# Generated by Django 4.2.4 on 2023-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0069_remove_loan_customer_delete_loan_req_delete_menu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('confirm', 'Approve')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
    ]
