# Generated by Django 4.2.4 on 2023-08-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0070_delete_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_approval',
            name='Deposit_Confirmation',
            field=models.CharField(choices=[('reject', 'Reject'), ('pending', 'Pending'), ('confirm', 'Approve')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_approval',
            name='Approval',
            field=models.CharField(choices=[('approve', 'Approve'), ('pending', 'Pending'), ('reject', 'Reject')], default='pending', max_length=200),
        ),
    ]
